name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Despliegue en nuget de ManagerEasySendEmailSmtp
      id: publish_nuget_ManagerEasySendEmailSmtp
      uses: rohith/publish-nuget@v2
      with:
          # Filepath of the project to be packaged , relative to root of repository
          PROJECT_FILE_PATH:  ManagerEasySendEmailSmtp/ManagerEasySendEmailSmtp.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
     
    - name: Despliegue en nuget de la inyeccion de dependencias del ManagerEasySendEmailSmtp
      id: publish_nuget_injectionManagerEasySendEmailSmtp
      uses: rohith/publish-nuget@v2
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ManagerEasySendEmailSmtp.Injection/ManagerEasySendEmailSmtp.Injection.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
